[package]
name = "realtime-drawing"
version = "0.1.0"
authors = ["koalefant <koalefant@fastmail.com>"]
edition = "2018"

[dependencies]
glam = "*"

[dev-dependencies]
miniquad = "0.3.0-alpha.30"

[lib]
name = "realtime_drawing"
